### ISSUE TITLE
Missing input parameters in readme.md

### ISSUE THREAD

**Issue by escherstair** [torizon/torizon-deb-ci#6]
readme.md lists the supported input parameters.
But, looking inside [toradex-deb-ci.yml](https://github.com/torizon/torizon-deb-ci/blob/main/.github/workflows/toradex-deb-ci.yml) I see that the following ones are not listed:

- extra-docker-args
- extra-repo-keys
- extra-apt-preferences
- before-build-hook

Can someone add them to the readme?

Morover, can someone add to the readme.md which syntax I should use to specify mutiple packages in `extra-packages` (as an example)?
I think they should be listed separated by space, but it's better to clarify it.

**Comment by escherstair** [comment]
@leonheldattoradex @charles2910 
did you have a chance to review the documentation?

Thanks

**Comment by charles2910** [comment]
Done! thanks for reporting @escherstair
